- name: Marp CLI Action
  uses: KoharaKazuya/marp-cli-action@v2.0.0
  
  - name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./
